#!/bin/bash

ASSETS=(
    "assets/images/about/gradient-top.png"
    "assets/images/about/gradient-bottom.png"
    "assets/images/common/places/1.png"
    "assets/images/common/places/0.png"
    "assets/images/common/places/1.png"
    "assets/images/common/places/2.png"
    "assets/images/common/places/3.png"
    "assets/images/common/places/4.png"
    "assets/images/common/logos/appstore.png"
    "assets/images/track/touchglow/blue.png"
    "assets/images/track/cars/blue.png"
    "assets/images/common/logos/chrome-experiment.png"
    "assets/images/common/logos/chrome.png"
    "assets/images/common/close.png"
    "assets/images/lineup/dotted-line.png"
    "assets/images/common/devices/droid-razr.png"
    "assets/images/common/places/empty.png"
    "assets/images/lineup/fade-left.png"
    "assets/images/lineup/fade-right.png"
    "assets/images/common/devices/galaxy-nexus.png"
    "assets/images/track/loader/glow.png"
    "assets/images/track/touchglow/green.png"
    "assets/images/track/cars/green.png"
    "assets/images/common/devices/ipad-mini.png"
    "assets/images/common/devices/ipad.png"
    "assets/images/common/devices/iphone-4.png"
    "assets/images/common/devices/iphone-5.png"
    "assets/images/track/name-bg.png"
    "assets/images/common/devices/nexus-4.png"
    "assets/images/common/devices/nexus-7.png"
    "assets/images/common/devices/nexus-10.png"
    "assets/images/track/touchglow/orange.png"
    "assets/images/track/cars/orange.png"
    "assets/images/common/logos/play.png"
    "assets/images/common/logos/racer-large-mobile.png"
    "assets/images/common/logos/racer-large.png"
    "assets/images/common/logos/racer-small.png"
    "assets/images/common/logos/racer.png"
    "assets/images/common/spin-loader.png"
    "assets/images/track/touchglow/red.png"
    "assets/images/track/cars/red.png"
    "assets/images/common/devices/samsung-epic-4g.png"
    "assets/images/common/devices/samsung-galaxy-ace.png"
    "assets/images/common/devices/samsung-galaxy-note-2.png"
    "assets/images/common/devices/samsung-galaxy-s2.png"
    "assets/images/common/devices/samsung-galaxy-s3.png"
    "assets/images/common/devices/samsung-galaxy-tab-2.png"
    "assets/images/common/devices/samsung-galaxy-y.png"
    "assets/images/track/loader/scan.png"
    "assets/images/track/banner/shadow.png"
    "assets/images/common/logos/share.png"
    "assets/images/track/startline.png"
    "assets/images/lineup/tick.png"
    "assets/images/track/loader/track.png"
    "assets/images/track/win-outline.gif"
    "assets/images/track/touchglow/yellow.png"
    "assets/images/track/cars/yellow.png"
    "assets/images/lineup/you-triangle-dark.png"
    "assets/images/lineup/you-triangle.png"
)

BASE_URL="https://storage.googleapis.com/chrome-racer-static"

for asset in "${ASSETS[@]}"; do
    url="$BASE_URL/$asset"
    filepath="downloaded_assets/$asset"  # Assuming you want to download to a directory named "downloaded_assets"
    mkdir -p "$(dirname "$filepath")"     # Create directories if they don't exist
    curl -s "$url" -o "$filepath"         # Use -s to silence curl's progress output
done